apiVersion: v1
kind: Service
metadata:
  name: fishing-forum-postgres
spec:
  selector:
    app: fishing-forum-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
