apiVersion: apps/v1
kind: Deployment
metadata:
  name: fishing-forum-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fishing-forum-postgres
  template:
    metadata:
      labels:
        app: fishing-forum-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: fishing_forum
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: fishing-forum-secrets
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fishing-forum-secrets
                  key: DB_PASS
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}
