apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  labels:
    app.kubernetes.io/name: fishnet
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
